name: Deploy to AWS
inputs:
  docker_tag:
    description: "Commit short SHA"
    required: true
    type: string
  stack_name:
    required: true
    type: string
  aws_region:
    required: true
    type: string
  pulumi_command:
    type: string
    default: up
  pulumi_diff:
    default: "false"
  PULUMI_ACCESS_TOKEN:
    required: true
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true
runs:
  using: composite
  steps:
    - run: |
        pulumi stack select -c ${{ inputs.stack_name }}
        pulumi config -s ${{ inputs.stack_name }} set aws:region ${{ inputs.aws_region }} --non-interactive
      shell: bash
      working-directory: infra/aws
      env:
        PULUMI_ACCESS_TOKEN: ${{ inputs.PULUMI_ACCESS_TOKEN }}
    - uses: pulumi/actions@v5
      id: pulumi
      with:
        command: ${{ inputs.pulumi_command }}
        diff: ${{ inputs.pulumi_diff }}
        stack-name: ${{ inputs.stack_name }}
        upsert: false
        work-dir: infra/aws
      env:
        PULUMI_ACCESS_TOKEN: ${{ inputs.PULUMI_ACCESS_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ inputs.aws_region }}
        SCROLL_BADGE_SERVICE_IMAGE_TAG: ${{ inputs.docker_tag }}
