export const getIamSecrets = (
  SCROLL_SECRETS_ARN: string,
  VC_SECRETS_ARN: string
) => [
  {
    name: "SCROLL_RPC_URL",
    valueFrom: `${SCROLL_SECRETS_ARN}:SCROLL_RPC_URL::`,
  },
  {
    name: "SCROLL_EAS_SCAN_URL",
    valueFrom: `${SCROLL_SECRETS_ARN}:SCROLL_EAS_SCAN_URL::`,
  },
  {
    name: "PASSPORT_SCORE_SCHEMA_UID",
    valueFrom: `${SCROLL_SECRETS_ARN}:PASSPORT_SCORE_SCHEMA_UID::`,
  },
  {
    name: "PASSPORT_SCORE_ATTESTER_CONTRACT_ADDRESS",
    valueFrom: `${SCROLL_SECRETS_ARN}:PASSPORT_SCORE_ATTESTER_CONTRACT_ADDRESS::`,
  },
  {
    name: "ATTESTER_PROXY_ADDRESS",
    valueFrom: `${SCROLL_SECRETS_ARN}:ATTESTER_PROXY_ADDRESS::`,
  },
  {
    name: "SCROLL_BADGE_SCHEMA_UID",
    valueFrom: `${SCROLL_SECRETS_ARN}:SCROLL_BADGE_SCHEMA_UID::`,
  },
  {
    name: "SCROLL_BADGE_ATTESTATION_SIGNER_PRIVATE_KEY",
    valueFrom: `${VC_SECRETS_ARN}:SCROLL_BADGE_ATTESTATION_SIGNER_PRIVATE_KEY::`,
  },
];
