name: Library - Deploy only
on:
  workflow_call:
    inputs:
      commit:
        description: "Leave blank to use current HEAD, or provide an override commit SHA"
        type: string
        required: false
      environment:
        description: "Environment to deploy to"
        type: string
        required: true

jobs:
  ref:
    name: Load Commit Ref
    runs-on: ubuntu-latest
    steps:
      - id: ref
        uses: ./.github/actions/load_commit_ref
        with:
          commit: ${{ inputs.commit }}

    outputs:
      version_tag: ${{ steps.ref.outputs.version_tag }}
      docker_tag: ${{ steps.ref.outputs.sha_short }}
      refspec: ${{ steps.ref.outputs.refspec }}

  deploy_preview:
    name: Preview - Deploying AWS Infra
    needs: [ref]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.ref.outputs.refspec }}
          fetch-depth: 0
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          AWS_ACCESS_KEY_ID: op://DevOps/passport-scroll-badge-service-${{ inputs.environment }}-secrets/service/AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: op://DevOps/passport-scroll-badge-service-${{ inputs.environment }}-secrets/service/AWS_SECRET_ACCESS_KEY
          PULUMI_ACCESS_TOKEN: op://DevOps/passport-scroll-badge-service-${{ inputs.environment }}-secrets/service/PULUMI_ACCESS_TOKEN
          ROUTE_53_DOMAIN: op://DevOps/passport-scroll-badge-service-${{ inputs.environment }}-env/service/ROUTE_53_DOMAIN
          SCROLL_SECRETS_ARN: op://DevOps/passport-scroll-badge-service-${{ inputs.environment }}-env/service/SCROLL_SECRETS_ARN
          VC_SECRETS_ARN: op://DevOps/passport-scroll-badge-service-${{ inputs.environment }}-env/service/VC_SECRETS_ARN
      - name: Prepare to Deploy to AWS
        uses: ./.github/actions/prepare_deploy_to_aws
      - name: Preview Deploy
        uses: ./.github/actions/deploy_to_aws
        with:
          docker_tag: ${{ needs.ref.outputs.docker_tag }}
          stack_name: gitcoin/scroll-badge-service/${{ inputs.environment }}
          aws_region: us-west-2
          pulumi_command: preview
          pulumi_diff: true
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ env.PULUMI_ACCESS_TOKEN }}
          ROUTE_53_DOMAIN: ${{ env.ROUTE_53_DOMAIN }}
          SCROLL_SECRETS_ARN: ${{ env.SCROLL_SECRETS_ARN }}
          VC_SECRETS_ARN: ${{ env.VC_SECRETS_ARN }}

  deploy_confirm:
    name: Review Approval Pending
    needs: [ref, deploy_preview]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Approve Release to Review (check pulumi preview)
        run: |
          echo "Ref" ${{ needs.ref.outputs.refspec }}

  deploy_backends:
    name: Deploying AWS Infra
    needs: [ref, deploy_preview, deploy_confirm]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.ref.outputs.refspec }}
          fetch-depth: 0
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          AWS_ACCESS_KEY_ID: op://DevOps/passport-scroll-badge-service-${{ inputs.environment }}-secrets/service/AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: op://DevOps/passport-scroll-badge-service-${{ inputs.environment }}-secrets/service/AWS_SECRET_ACCESS_KEY
          PULUMI_ACCESS_TOKEN: op://DevOps/passport-scroll-badge-service-${{ inputs.environment }}-secrets/service/PULUMI_ACCESS_TOKEN
          ROUTE_53_DOMAIN: op://DevOps/passport-scroll-badge-service-${{ inputs.environment }}-env/service/ROUTE_53_DOMAIN
          SCROLL_SECRETS_ARN: op://DevOps/passport-scroll-badge-service-${{ inputs.environment }}-env/service/SCROLL_SECRETS_ARN
          VC_SECRETS_ARN: op://DevOps/passport-scroll-badge-service-${{ inputs.environment }}-env/service/VC_SECRETS_ARN
      - name: Prepare to Deploy to AWS
        uses: ./.github/actions/prepare_deploy_to_aws
      - name: Deploy Review
        uses: ./.github/actions/deploy_to_aws
        with:
          docker_tag: ${{ needs.ref.outputs.docker_tag }}
          stack_name: gitcoin/scroll-badge-service/${{ inputs.environment }}
          aws_region: us-west-2
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ env.PULUMI_ACCESS_TOKEN }}
          ROUTE_53_DOMAIN: ${{ env.ROUTE_53_DOMAIN }}
          SCROLL_SECRETS_ARN: ${{ env.SCROLL_SECRETS_ARN }}
          VC_SECRETS_ARN: ${{ env.VC_SECRETS_ARN }}
