name: Deploy to Production
on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Leave blank to use current HEAD, or provide an override commit SHA"
        type: string
        required: false
    secrets:
      PULUMI_ACCESS_TOKEN:
        required: true

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy_generic.yml
    with:
      commit: ${{ inputs.commit }}
      environment: production
    secrets: inherit
